name: Run tests and deploy to GitHub pages if successful

on:
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Setup Node 🔧
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install and run unit tests 🔧
        run: | 
          npm install --force
          npm run test:unit

  deploy-gh-pages:
    needs: run-unit-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Setup Node 🔧
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install and build 🔧
        run: |
          npm install --force
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: docs